Add LGPL header
git-svn-id: https://svn.code.sf.net/p/taco/taco/trunk@883 cd552e4a-acb0-437c-bff1-0b624b0be6ef

diff --git a/taco/misc/taco-config.in b/taco/misc/taco-config.in
--- a/taco/misc/taco-config.in
+++ b/taco/misc/taco-config.in
@@ -1,4 +1,22 @@
 #! /bin/sh
+# Toolkit for building distributed control systems or any other distributed system.
+#
+# Copyright (c) 2003-2005 Jens Krüger <jkrueger1@users.sf.net>
+#
+# This library is free software; you can redistribute it and/or
+# modify it under the terms of the GNU Lesser General Public
+# License as published by the Free Software Foundation; either
+# version 2.1 of the License, or (at your option) any later version.
+#
+# This library is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# Lesser General Public License for more details.
+#
+# You should have received a copy of the GNU Lesser General Public
+# License along with this library; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
+#
 
 if test -z $1 ; then
 	echo "Usage: $0 option"
@@ -26,8 +44,8 @@ case $1 in
 	--initdir) echo "$initdir" ;;
 	--pythondir) echo "$pythondir" ;;
 	*)
-		echo "error: unknown option: $1"
-		exit 1
-		;;
+	echo "error: unknown option: $1"
+	exit 1
+	;;
 esac
 exit 0
